import {
  DEFAULT_DAY_OF_WEEK,
  DEFAULT_EDITOR_WIDTH,
  DEFAULT_SHORTCUTS,
  DEFAULT_SIDEBAR_WIDTH,
} from '$constants';
import { getDefaultAccentColor } from '$constants/colorSchemes';
import { DEFAULT_COLOR_SCHEME_ID } from '$types/color';
import type { SettingsState } from '$types/settings';

const defaultAccentColor = getDefaultAccentColor();

export const defaultState: SettingsState = {
  theme: 'system',
  accentColor: defaultAccentColor,
  autoSync: true,
  syncInterval: 5,
  syncOnStartup: true,
  syncOnReconnect: true,
  confirmBeforeDeletion: true,
  confirmBeforePermanentDelete: true,
  confirmBeforeDeleteCalendar: true,
  confirmBeforeDeleteAccount: true,
  confirmBeforeDeleteTag: true,
  deleteSubtasksWithParent: 'delete',
  startOfWeek: DEFAULT_DAY_OF_WEEK,
  timeFormat: '12',
  dateFormat: 'MMM d, yyyy',
  notifications: true,
  notifyReminders: true,
  notifyOverdue: true,
  defaultCalendarId: null,
  keyboardShortcuts: DEFAULT_SHORTCUTS,
  defaultPriority: 'none',
  defaultStatus: 'needs-action',
  defaultPercentComplete: 0,
  defaultTags: [],
  defaultStartDate: 'none',
  defaultDueDate: 'none',
  defaultReminders: [],
  defaultRrule: undefined,
  defaultRepeatFrom: 0,
  sidebarCollapsed: false,
  sidebarWidth: DEFAULT_SIDEBAR_WIDTH,
  taskEditorWidth: DEFAULT_EDITOR_WIDTH,
  onboardingCompleted: false,
  expandedAccountIds: [],
  defaultAccountsExpanded: true,
  localSectionCollapsed: false,
  accountsSectionCollapsed: false,
  filtersSectionCollapsed: false,
  tagsSectionCollapsed: false,
  enableSystemTray: true,
  systemTrayAppliedValue: true,
  hideDockIconWhenWindowClosed: true,
  showWindowOnLoginLaunch: false,
  checkForUpdatesAutomatically: true,
  confirmBeforeQuit: true,
  confirmBeforeQuitAppliedValue: true,
  defaultAllDayReminderHour: 17,
  allDayReminderNotificationsEnabled: true,
  colorScheme: DEFAULT_COLOR_SCHEME_ID,
  colorSchemeFlavor: null,
  accentColorByScheme: { [DEFAULT_COLOR_SCHEME_ID]: defaultAccentColor },
  useAccentColorForCheckboxes: false,
  taskListDensity: 'comfortable',
  defaultTagColor: 'accent',
  defaultCalendarColor: 'accent',
  quietHoursEnabled: false,
  quietHoursStart: 22,
  quietHoursEnd: 8,
  editorFieldVisibility: {
    status: true,
    description: true,
    url: true,
    dates: true,
    repeat: true,
    priority: true,
    calendar: true,
    tags: true,
    reminders: true,
    subtasks: true,
  },
  editorFieldOrder: [
    'status',
    'description',
    'url',
    'dates',
    'repeat',
    'priority',
    'calendar',
    'tags',
    'reminders',
    'subtasks',
  ],
  taskBadgeVisibility: {
    startDate: true,
    dueDate: true,
    tags: true,
    calendar: true,
    url: true,
    status: true,
    repeat: true,
    subtasks: true,
  },
  taskBadgeOrder: [
    'startDate',
    'dueDate',
    'tags',
    'calendar',
    'url',
    'status',
    'repeat',
    'subtasks',
  ],
  quickTimePresets: { morning: 540, afternoon: 720, evening: 1020, night: 1260 },
  connectivityCheckEnabled: true,
  connectivityCheckUrl: '',
  connectivityCheckInterval: 30,
  windowDecorationsMode: 'auto',
  windowDecorationsAppliedValue: 'auto',
  enablePush: false,
  ntfyServerUrl: 'https://ntfy.sh',
  hasSeenRecentlyDeletedToast: false,
};
