import {
  DEFAULT_DAY_OF_WEEK,
  DEFAULT_EDITOR_WIDTH,
  DEFAULT_SHORTCUTS,
  DEFAULT_SIDEBAR_WIDTH,
} from '$constants';
import { DEFAULT_COLOR_SCHEME_ID } from '$constants/color';
import { NTFY_DIRECT_PROVIDER_ID } from '$types/push/providers';
import type { SettingsState } from '$types/settings/state';
import { getDefaultAccentColor } from '$utils/color/scheme';

const defaultAccentColor = getDefaultAccentColor();

export const defaultState: SettingsState = {
  theme: 'system',
  accentColor: defaultAccentColor,
  autoSync: true,
  syncInterval: 15,
  syncOnStartup: true,
  syncOnReconnect: true,
  confirmBeforeMoveToRecentlyDeleted: false,
  deleteSubtasksWithParent: 'delete',
  autoEmptyRecentlyDeleted: true,
  recentlyDeletedRetentionDays: 30,
  startOfWeek: DEFAULT_DAY_OF_WEEK,
  timeFormat: '12',
  dateFormat: 'MMM d, yyyy',
  notifications: true,
  notifyReminders: true,
  notifyOverdue: true,
  showAppIconBadge: true,
  defaultCalendarId: null,
  defaultCalendarIdManuallyChanged: false,
  preferCalDAVCalendarForNewTasks: true,
  keyboardShortcuts: DEFAULT_SHORTCUTS,
  defaultPriority: 'none',
  defaultStatus: 'needs-action',
  defaultPercentComplete: 0,
  syncStatusProgress: true,
  progressIncrement: 5,
  completeInProcessTasks: true,
  defaultTags: [],
  defaultStartDate: 'none',
  defaultStartTime: null,
  defaultDueDate: 'none',
  defaultDueTime: null,
  defaultReminders: [],
  defaultRrule: undefined,
  defaultRepeatFrom: 0,
  sidebarCollapsed: false,
  sidebarWidth: DEFAULT_SIDEBAR_WIDTH,
  taskEditorWidth: DEFAULT_EDITOR_WIDTH,
  onboardingCompleted: false,
  expandedAccountIds: [],
  localSectionCollapsed: false,
  accountsSectionCollapsed: false,
  filtersSectionCollapsed: false,
  tagsSectionCollapsed: false,
  showLocalSection: true,
  showAccountsSection: true,
  showFiltersSection: true,
  showTagsSection: true,
  showSidebarTaskCounts: true,
  sidebarSectionOrder: ['filters', 'local', 'accounts', 'tags'],
  defaultLaunchView: 'last-view',
  enableSystemTray: true,
  systemTrayAppliedValue: true,
  hideDockIconWhenWindowClosed: true,
  showWindowOnLoginLaunch: false,
  enableSystemTrayExplicitlySet: false,
  windowDecorationStyle: 'integrated',
  checkForUpdatesAutomatically: true,
  confirmBeforeQuit: true,
  confirmBeforeQuitAppliedValue: true,
  defaultAllDayReminderHour: 17,
  allDayReminderNotificationsEnabled: true,
  colorScheme: DEFAULT_COLOR_SCHEME_ID,
  colorSchemeFlavor: null,
  accentColorByScheme: { [DEFAULT_COLOR_SCHEME_ID]: defaultAccentColor },
  useAccentColorForCheckboxes: false,
  showCursorPointers: true,
  taskListDensity: 'comfortable',
  taskTitleLines: 'one',
  defaultTagColor: 'accent',
  defaultCalendarColor: 'accent',
  quietHoursEnabled: false,
  quietHoursStart: 22,
  quietHoursEnd: 8,
  editorFieldVisibility: {
    status: true,
    progress: true,
    description: true,
    url: true,
    dates: true,
    repeat: true,
    priority: true,
    calendar: true,
    tags: true,
    reminders: true,
    subtasks: true,
  },
  editorFieldOrder: [
    'status',
    'progress',
    'description',
    'url',
    'dates',
    'repeat',
    'priority',
    'calendar',
    'tags',
    'reminders',
    'subtasks',
  ],
  taskBadgeVisibility: {
    startDate: true,
    dueDate: true,
    tags: true,
    calendar: true,
    url: true,
    status: true,
    snooze: true,
    repeat: true,
    subtasks: true,
  },

  taskBadgeOrder: [
    'startDate',
    'dueDate',
    'tags',
    'calendar',
    'url',
    'status',
    'snooze',
    'repeat',
    'subtasks',
  ],

  quickTimePresets: { morning: 540, afternoon: 720, evening: 1020, night: 1260 },
  workingDays: ['mo', 'tu', 'we', 'th', 'fr'],
  connectivityCheckEnabled: true,
  connectivityCheckUrl: '',
  connectivityCheckInterval: 30,
  connectivityRequestTimeout: 5,
  caldavRequestTimeout: 15,
  networkProxyMode: 'system',
  networkProxyHost: '',
  networkProxyPort: '',
  enablePush: false,
  enforceVapid: false,
  pushProvider: NTFY_DIRECT_PROVIDER_ID,
  ntfyServerUrl: '',
  mozillaAutopushWebsocketUrl: '',
  mozillaAutopushEndpointUrl: '',
  notificationActions: {
    complete: true,
    snooze: true,
    snoozeDurations: [
      { id: '30m', value: 30, unit: 'minutes' },
      { id: '1h', value: 1, unit: 'hours' },
    ],
    order: ['complete', 'snooze'],
  },
  hasSeenRecentlyDeletedToast: false,
};
